import json
from PIL import Image
# Thor Polysonic Synthesizer. Front picture = _captures_batchE/thor_front_raw.jpg (pts in picture px). Back = stitched top+bottom.
NT="no tooltip in Reason (hovered 1.2 s)"
T=lambda s:'tooltip "%s"'%s
NOSLOT="Remote item exists but is beyond the 48 knob slots of our remotemap (not mapped)"
notes={}
for ln in open("_captures_batchE/thor_notes.txt"):
    p=ln.rstrip("\n").split("|",1)
    if len(p)==2: notes[p[0]]=p[1]
pts={a:(x,y) for a,x,y in json.load(open("_captures_batchE/thor_pts.json"))}
def c(k):
    v=notes.get(k)
    if v is None or v.startswith("(not hovered"): return "not hovered (indicator light / sub-part of a hovered control)"
    if v.startswith("(no tooltip"): return NT
    return T(v)
F=[];CF={}
def f(key,label,what,name=None,slot=None,typ="B",hw=None,hh=None,conf="high",why="",chk=None,mode=None):
    x,y=pts[key]
    d={"K":(15,15),"B":(9,9),"S":(8,26),"D":(30,10)}[typ]
    hw=hw or d[0]; hh=hh or d[1]
    if name and slot is None and not why: why=NOSLOT
    F.append([label,what,name,slot,[x,y],[hw,hh],typ,conf,why]+([mode] if mode else [])); CF[label]=chk or c(key)
f("fold","(triangle)","Fold/unfold device",typ="B",conf="medium")
f("range","Range display","Keyboard range (number of keys)",typ="D",hw=26,hh=12,conf="medium")
f("rangearrows","(range arrows)","Range down/up",typ="B",hw=12,hh=14,conf="medium")
f("patchdisp","Patch display","Patch name display","Patch Name",None,"D",150,16,"medium","Remote item 'Patch Name'; display gave no tooltip; NOT proven")
f("patcharrows","(patch arrows)","Previous / next patch","Select Previous Patch",None,"B",12,14,why="lower half = Select Next Patch, not hovered")
f("patchfolder","(patch folder)","Browse patch",typ="B",hw=13,hh=12)
f("patchdisk","(patch disk)","Save patch",typ="B",hw=13,hh=12)
f("tape","Patch name tape","Patch name tape","Device Name",None,"D",50,40,"medium","Remote item 'Device Name'; convention from earlier devices")
f("wheelP","PITCH BEND wheel","Pitch bend wheel","Pitch Bend",None,"S",12,48,"medium","Remote item 'Pitch Bend' matched by label; wheel gave no tooltip; NOT proven")
f("wheelM","MOD wheel","Mod wheel","Mod Wheel",None,"S",12,48,"medium","Remote item 'Mod Wheel' matched by label; no tooltip; NOT proven")
f("poly","POLYPHONY display","Polyphony (voices)","Polyphony",None,"D",24,12,"medium","matched by meaning; no tooltip; NOT proven")
f("polyarrows","(polyphony arrows)","Polyphony down/up",typ="B",hw=12,hh=14,conf="medium")
f("relpoly","RELEASE POLYPHONY display","Release polyphony (voices)","Release Polyphony",None,"D",24,12,"medium","matched by meaning; no tooltip; NOT proven")
f("relarrows","(release polyphony arrows)","Release polyphony down/up",typ="B",hw=12,hh=14,conf="medium")
f("kmLegato","KEY MODE: Mono legato","Key mode: mono legato",typ="B",conf="medium")
f("kmRetrig","KEY MODE: Mono retrig","Key mode: mono retrig",typ="B",conf="medium")
f("kmPoly","KEY MODE: Polyphonic","Key mode: polyphonic",typ="B",conf="medium")
f("kmMODE","KEY MODE (mode button)","Key mode / Remote item 'Key Mode'","Key Mode",None,"B",12,10,"medium","tooltip 'Key Mode'; Remote item 'Key Mode' matched")
f("portaK","PORTAMENTO knob","Portamento","Portamento",None,"K",14,14)
f("portaSw","PORTAMENTO switch (OFF/ON/AUTO)","Portamento mode","Portamento Mode",None,"B",10,24)
f("showprog","Show Programmer","Show/hide the programmer panel",typ="B",hw=60,hh=10)
f("trigMIDI","TRIGGER: MIDI","Note trigger: MIDI","Note Trigger MIDI",None,"B")
f("trigSTEP","TRIGGER: STEP SEQ","Note trigger: step sequencer","Note Trigger Step Seq",None,"B")
f("noteon","NOTE ON light","Note-on light","Note On Indicator",None,"D",8,8,"medium","Remote item 'Note On Indicator'; light gave no tooltip; NOT proven")
f("rot1","ROTARY 1","Rotary 1 knob","Rotary 1",None,"K")
f("rot1label","ROTARY 1 label display","Rotary 1 label (assignment name)",typ="D",hw=34,hh=8)
f("rot2","ROTARY 2","Rotary 2 knob","Rotary 2",None,"K")
f("rot2label","ROTARY 2 label display","Rotary 2 label (assignment name)",typ="D",hw=34,hh=8)
f("btn1","BUTTON 1","Button 1","Button 1",None,"B",chk=T("Button 1"))
f("btn1disp","BUTTON 1 display","Button 1 assignment display",typ="D",hw=30,hh=8)
f("btn1arrows","(button 1 arrows)","Button 1 destination prev/next",typ="B",hw=10,hh=12,conf="medium")
f("btn1label","BUTTON 1 label","Button 1 label",typ="D",hw=30,hh=8)
f("btn2","BUTTON 2","Button 2","Button 2",None,"B",chk=T("Button 2"))
f("btn2disp","BUTTON 2 display","Button 2 assignment display",typ="D",hw=30,hh=8)
f("btn2arrows","(button 2 arrows)","Button 2 destination prev/next",typ="B",hw=10,hh=12,conf="medium")
f("btn2label","BUTTON 2 label","Button 2 label",typ="D",hw=30,hh=8)
f("master","MASTER VOLUME","Master level","Master Level",48,"K",30,30)
f("amfrom","OSC 1 AM FROM OSC 2","Osc 1 amplitude modulation from osc 2","Osc 1 AM From Osc 2",None,"K")
f("mo_menu","OSC 1 type menu","Osc 1 type (Multi Osc)","Osc 1 Type",1,"D",50,8,"medium","Remote 'Osc 1 Type' (slot 1) matched by meaning; menu gave no tooltip; NOT proven")
f("mo_kbd","OSC 1 KBD","Osc 1 keyboard tracking","Osc 1 Kbd",None,"K")
f("mo_oct","OSC 1 OCT","Osc 1 octave","Osc 1 Oct",2,"K")
f("mo_semi","OSC 1 SEMI","Osc 1 semitone","Osc 1 Semi",3,"K")
f("mo_tune","OSC 1 TUNE","Osc 1 fine tune","Osc 1 Tune",4,"K")
f("mo_detune","MULTI OSC DETUNE MODE display","Multi osc detune mode",typ="D",hw=32,hh=8,conf="medium")
f("mo_detarrows","(detune mode arrows)","Detune mode prev/next",typ="B",hw=10,hh=12,conf="medium")
f("mo_amt","OSC 1 DETUNE AMT","Osc 1 detune amount","Osc 1 Mod",5,"K",conf="low",why="tooltip 'Osc 1 Detune Amt'; Remote 'Osc 1 Mod' (slot 5) matched by position in the osc block, NOT proven")
f("mo_off","OSC 1 MULTI WAVE","Osc 1 multi waveform select",typ="B",conf="low",why="tooltip 'Osc 1 Multi Wave' belonged to the point near this one; position NOT proven")
for i in (1,2,3,4): f("mo_led%d"%i,"OSC 1 mode LED %d"%i,"Osc 1 multi osc mode light %d"%i,typ="D",hw=6,hh=6,conf="low")
f("wt_menu","OSC 2 type menu","Osc 2 type (Wavetable Osc)","Osc 2 Type",6,"D",50,8,"medium","Remote 'Osc 2 Type' (slot 6) matched by meaning; no tooltip; NOT proven")
f("wt_kbd","OSC 2 KBD","Osc 2 keyboard tracking","Osc 2 Kbd",None,"K")
f("wt_oct","OSC 2 OCT","Osc 2 octave","Osc 2 Oct",7,"K")
f("wt_semi","OSC 2 SEMI","Osc 2 semitone","Osc 2 Semi",8,"K")
f("wt_tune","OSC 2 TUNE","Osc 2 fine tune","Osc 2 Tune",9,"K")
f("wt_table","TABLE SELECT display","Osc 2 wavetable name",typ="D",hw=50,hh=10)
f("wt_tablearrows","(table arrows)","Wavetable prev/next",typ="B",hw=10,hh=12,conf="medium")
f("wt_pos","OSC 2 POSITION","Osc 2 wavetable position","Osc 2 Mod",10,"K",conf="low",why="tooltip 'Osc 2 Pos'; Remote 'Osc 2 Mod' (slot 10) matched by position in the osc block, NOT proven")
f("wt_xfade","OSC 2 X-FADE","Osc 2 wavetable smooth crossfade",typ="B",conf="medium",why="tooltip 'Osc 2 Wavetable Smooth X fade'; no Remote item")
f("wt_xled","OSC 2 X-FADE light","Osc 2 x-fade light",typ="D",hw=6,hh=6,conf="low")
f("sync1","OSC 2 SYNC","Osc 2 sync to osc 1","Osc 2 Sync To Osc 1",None,"B")
f("bw1","OSC 2 SYNC BW","Osc 2 sync bandwidth","Osc 2 Sync BW",None,"K",conf="medium",why="no tooltip; Remote 'Osc 2 Sync BW' matched by position; NOT proven")
f("sync2","OSC 3 SYNC","Osc 3 sync to osc 1","Osc 3 Sync To Osc 1",None,"B")
f("bw2","OSC 3 SYNC BW","Osc 3 sync bandwidth","Osc 3 Sync BW",None,"K")
f("an_menu","OSC 3 type menu","Osc 3 type (Analog Osc)","Osc 3 Type",11,"D",50,8,"medium","Remote 'Osc 3 Type' (slot 11) matched by meaning; no tooltip; NOT proven")
f("an_kbd","OSC 3 KBD","Osc 3 keyboard tracking","Osc 3 Kbd",None,"K")
f("an_oct","OSC 3 OCT","Osc 3 octave","Osc 3 Oct",12,"K")
f("an_semi","OSC 3 SEMI","Osc 3 semitone","Osc 3 Semi",13,"K")
f("an_tune","OSC 3 TUNE","Osc 3 fine tune","Osc 3 Tune",14,"K")
for i in (1,2,3,4): f("an_w%d"%i,"OSC 3 wave button %d"%i,"Osc 3 analog waveform %d"%i,typ="B",hw=7,hh=7,conf="medium",chk=c("an_w1") if i==1 else "not hovered; same group as the first wave button, which gave no tooltip")
f("an_pw","OSC 3 PW","Osc 3 pulse width","Osc 3 Mod",15,"K",conf="low",why="tooltip 'Osc 3 PW'; Remote 'Osc 3 Mod' (slot 15) matched by position in the osc block, NOT proven")
f("an_off","OSC 3 ANALOG WAVE","Osc 3 analog waveform select",typ="B",conf="low",why="tooltip 'Osc 3 Analog Wave' belonged to the point near this one; position NOT proven")
f("f1_menu","FILTER 1 type menu","Filter 1 type (Low Pass Ladder)","Filter 1 Type",19,"D",70,8,"medium","Remote 'Filter 1 Type' (slot 19) matched by meaning; no tooltip; NOT proven")
f("f1_self","FILTER 1 SELF OSC","Filter 1 self oscillation","Filter 1 Self Osc",None,"B")
for i in range(1,6): f("f1_t%d"%i,"FILTER 1 slope button %d"%i,"Filter 1 ladder slope selector %d"%i,typ="B",hw=7,hh=7,conf="medium",chk=c("f1_t1") if i in (1,5) else "not hovered; same group, other buttons gave no tooltip")
f("f1_freq","FILTER 1 FREQ","Filter 1 frequency","Filter 1 Freq",20,"K",20,20)
f("f1_res","FILTER 1 RES","Filter 1 resonance","Filter 1 Res",21,"K")
f("f1_drive","FILTER 1 DRIVE","Filter 1 drive","Filter 1 Drive",22,"K")
f("f1_inv","FILTER 1 INV","Filter 1 envelope invert","Filter 1 Env Invert",None,"B")
f("f1_env","FILTER 1 ENV","Filter 1 envelope amount","Filter 1 Env Amount",23,"K")
f("f1_vel","FILTER 1 VEL","Filter 1 velocity","Filter 1 Velocity",None,"K")
f("f1_kbd","FILTER 1 KBD","Filter 1 keyboard tracking","Filter 1 Kbd",24,"K")
f("f1_mode","FILTER 1 slope selector","Filter 1 ladder slope",typ="B",conf="medium",why="tooltip 'Filter 1 Ladder Slope'; no Remote item")
f("f1_pwr","FILTER 1 power","Filter 1 on/off",typ="B",conf="low",why="no tooltip")
for n in (1,2,3):
    f("rt%d"%n,"OSC %d to FILTER 1"%n,"Route osc %d to filter 1"%n,"Osc %d To Filter 1 Enable"%n,None,"B")
    f("rb%d"%n,"OSC %d to FILTER 2"%n,"Route osc %d to filter 2"%n,"Osc %d To Filter 2 Enable"%n,None,"B")
f("mix_bal","MIXER BALANCE","Osc 1 and 2 balance","Osc 1 And 2 Balance",18,"K")
f("mix_s12","MIXER OSC 1+2 slider","Osc 1 and 2 level","Osc 1 And 2 Level",17,"S")
f("mix_s3","MIXER OSC 3 slider","Osc 3 level","Osc 3 Level",16,"S")
f("sh_on","SHAPER on","Shaper on/off","Shaper On",40,"B")
f("sh_type","SHAPER type menu","Shaper type","Shaper Type",None,"D",40,8,"medium","Remote 'Shaper Type' matched by meaning; no tooltip; NOT proven")
f("sh_arrows","(shaper type arrows)","Shaper type prev/next",typ="B",hw=10,hh=12,conf="medium")
f("sh_drive","SHAPER DRIVE","Shaper drive","Shaper Drive",41,"K")
f("amp_vel","AMP VEL","Amplifier velocity","Amplifier Velocity",None,"K")
f("amp_gain","AMP GAIN","Amplifier gain","Amplifier Gain",37,"K",18,18)
f("amp_pan","AMP PAN","Amplifier pan","Amplifier Pan",None,"K")
f("arrowL","SHAPER to FILTER 2","Shaper output to filter 2",typ="B",conf="medium",why="tooltip 'Shaper to Filter 2'; Remote 'Shaper Output Dest' may cover both arrows; NOT proven")
f("arrowR","SHAPER to AMP","Shaper output to amplifier",typ="B",conf="medium",why="tooltip 'Shaper to Amplifier'; see other arrow")
f("arrowB","FILTER 2 to AMP","Filter 2 output to amplifier","Filter2ToAmplifier Enable",None,"B")
f("f2_menu","FILTER 2 type menu","Filter 2 type (bypassed, folded view)","Filter 2 Type",25,"D",60,10,"medium","Remote 'Filter 2 Type' (slot 25); panel shows Filter 2 Bypass; no tooltip; NOT proven")
f("l1_key","LFO 1 KEY SYNC","LFO 1 key sync","LFO 1 Key Sync",None,"B")
f("l1_tempo","LFO 1 TEMPO SYNC","LFO 1 tempo sync","LFO 1 Tempo Sync",None,"B")
f("l1_rate","LFO 1 RATE","LFO 1 rate","LFO 1 Rate",38,"K")
f("l1_delay","LFO 1 DELAY","LFO 1 delay","LFO 1 Delay",None,"K")
f("l1_kbdf","LFO 1 KBD FOLLOW","LFO 1 keyboard follow","LFO 1 KbdFollow",None,"K")
f("l1_wave","LFO 1 WAVEFORM","LFO 1 waveform","LFO 1 Waveform",39,"D",30,16)
f("l1_arrows","(LFO 1 waveform arrows)","LFO 1 waveform prev/next",typ="B",hw=10,hh=12,conf="medium")
f("me_gate","MOD ENV GATE TRIG","Mod envelope gate trigger","Mod Env Gate Trig On",None,"B")
f("me_tempo","MOD ENV TEMPO SYNC","Mod envelope tempo sync","Mod Env Tempo Sync",None,"B")
f("me_loop","MOD ENV LOOP","Mod envelope loop","Mod Env Loop",None,"B")
f("me_delay","MOD ENV DELAY","Mod envelope delay","Mod Env Delay",None,"S")
f("me_A","MOD ENV A","Mod envelope attack","Mod Env Attack",None,"S")
f("me_D","MOD ENV D","Mod envelope decay","Mod Env Decay",None,"S")
f("me_R","MOD ENV R","Mod envelope release","Mod Env Release",None,"S")
f("fe_gate","FILTER ENV GATE TRIG","Filter envelope gate trigger","Filter Env Gate Trig On",None,"B")
for k,l,n,s in (("A","A","Attack",29),("D","D","Decay",30),("S","S","Sustain",31),("R","R","Release",32)):
    f("fe_"+k,"FILTER ENV "+l,"Filter envelope "+n.lower(),"Filter Env "+n,s,"S")
f("ae_gate","AMP ENV GATE TRIG","Amp envelope gate trigger","Amp Env Gate Trig On",None,"B")
for k,l,n,s in (("A","A","Attack",33),("D","D","Decay",34),("S","S","Sustain",35),("R","R","Release",36)):
    f("ae_"+k,"AMP ENV "+l,"Amp envelope "+n.lower(),"Amp Env "+n,s,"S")
f("dl_on","DELAY on","Delay on/off","Delay On",42,"B")
f("dl_sync","DELAY SYNC","Delay tempo sync","Delay Sync",None,"B")
f("dl_time","DELAY TIME","Delay time","Delay Time",44,"K")
f("dl_fback","DELAY F.BACK","Delay feedback","Delay Feedback",45,"K")
f("dl_rate","DELAY RATE","Delay modulation rate","Delay Rate",None,"K")
f("dl_amt","DELAY AMT","Delay modulation amount","Delay Amt",None,"K")
f("dl_dw","DELAY D/WET","Delay dry/wet","Delay Dry Wet",43,"K")
f("ch_on","CHORUS on","Chorus on/off","Chorus On",46,"B")
f("ch_delay","CHORUS DELAY","Chorus delay","Chorus Delay",None,"K")
f("ch_fback","CHORUS F.BACK","Chorus feedback","Chorus Feedback",None,"K")
f("ch_rate","CHORUS RATE","Chorus rate","Chorus Rate",None,"K")
f("ch_amt","CHORUS AMT","Chorus amount","Chorus Amt",None,"K")
f("ch_dw","CHORUS D/WET","Chorus dry/wet","Chorus Dry Wet",47,"K")
f("cf_menu","COMB FILTER type menu","Filter 3 type (Comb Filter)","Filter 3 Type",None,"D",70,8,"medium","Remote 'Filter 3 Type' matched by meaning; no tooltip; NOT proven")
f("cf_pwr","COMB FILTER power","Filter 3 on/off",typ="B",conf="low",why="no tooltip")
f("cf_drive","COMB DRIVE","Filter 3 drive","Filter 3 Drive",None,"K")
f("cf_freq","COMB FREQ","Filter 3 frequency","Filter 3 Freq",None,"K",20,20)
f("cf_res","COMB RES","Filter 3 resonance","Filter 3 Res",None,"K")
f("cf_p","COMB+","Comb filter positive",typ="B",conf="medium")
f("cf_m","COMB-","Comb filter negative",typ="B",conf="medium")
f("cf_mode","COMB MODE","Filter 3 comb preset",typ="B",conf="medium",why="tooltip 'Filter 3 Comb Preset'; no Remote item")
f("cf_inv","COMB INV","Filter 3 global envelope invert","Filter 3 Global Env Invert",None,"B")
f("cf_env","COMB ENV","Filter 3 global envelope amount","Filter 3 Global Env Amount",None,"K")
f("cf_vel","COMB VEL","Filter 3 velocity","Filter 3 Velocity",None,"K")
f("cf_kbd","COMB KBD","Filter 3 keyboard tracking","Filter 3 Kbd",None,"K")
f("ge_gate","GLOBAL ENV GATE TRIG","Global envelope gate trigger","Global Env Gate Trig On",None,"B")
f("ge_tempo","GLOBAL ENV TEMPO SYNC","Global envelope tempo sync","Global Env Tempo Sync",None,"B")
f("ge_loop","GLOBAL ENV LOOP","Global envelope loop","Global Env Loop",None,"B")
f("ge_delay","GLOBAL ENV DELAY","Global envelope delay","Global Env Delay",None,"S")
f("ge_A","GLOBAL ENV A","Global envelope attack","Global Env Attack",None,"S")
f("ge_hold","GLOBAL ENV HOLD","Global envelope hold","Global Env Hold",None,"S")
f("ge_D","GLOBAL ENV D","Global envelope decay","Global Env Decay",None,"S")
f("ge_S","GLOBAL ENV S","Global envelope sustain","Global Env Sustain",None,"S")
f("ge_R","GLOBAL ENV R","Global envelope release","Global Env Release",None,"S")
f("l2_key","LFO 2 KEY SYNC","LFO 2 key sync","LFO 2 Key Sync",None,"B")
f("l2_tempo","LFO 2 TEMPO SYNC","LFO 2 tempo sync","LFO 2 Tempo Sync",None,"B")
f("l2_rate","LFO 2 RATE","LFO 2 rate","LFO 2 Rate",None,"K")
f("l2_delay","LFO 2 DELAY","LFO 2 delay","LFO 2 Delay",None,"K")
f("l2_wave","LFO 2 WAVEFORM","LFO 2 waveform","LFO 2 Waveform",None,"D",30,16)
f("l2_arrows","(LFO 2 waveform arrows)","LFO 2 waveform prev/next",typ="B",hw=10,hh=12,conf="medium")
# --- modulation matrix: rows hovered = 1, 8, 12; the others follow the same pattern (inferred, not hovered)
INF="not hovered; same column as the hovered row, name follows the row pattern (row number from table order). Click to confirm before relying on it."
def mx(key,label,what,name,n,hov):
    f(key,label,what,name,None,"D",34,8,"medium" if not hov else "high",chk=(c(key) if hov else INF),
      why="" if hov else "inferred from pattern, not hovered") if False else None
def cell(key,label,what,name,kind,known=None,chk=None,typ="D"):
    f(key,label,what,name,None,typ,34 if typ=="D" else 9,8 if typ=="D" else 9,"high" if known else "medium",why="" if known else "inferred from the hovered row's pattern; not hovered",chk=chk if known else INF)
for i in range(1,8):
    p="mL%d_"%i
    cell(p+"src","MOD %d source menu"%i,"Mod %d source"%i,"Mod %d Source"%i if i<=6 else None,0,chk=NT,known=(i==1))
    cell(p+"amt","MOD %d dest amount"%i,"Mod %d destination amount"%i,"Mod %d Dest Amount"%i,0,known=(i==1),chk=T("Mod 1 Dest Amount: 15"))
    cell(p+"dest","MOD %d dest menu"%i,"Mod %d destination"%i,"Mod %d Dest"%i if i<=6 else None,0,chk=NT,known=(i==1))
    cell(p+"amt2","MOD %d scale amount"%i,"Mod %d scale amount"%i,"Mod %d Scale Amount"%i,0,known=(i==1),chk=T("Mod 1 Scale Amount: 0"))
    cell(p+"scale","MOD %d scale menu"%i,"Mod %d scale source"%i,None,0,chk=NT,known=(i==1))
    cell(p+"clr","MOD %d clear"%i,"Clear mod row %d"%i,None,0,chk=T("Clear Sources, Modulations and Scales"),known=(i==1),typ="B")
for j in range(1,5):
    n=7+j; p="mR%d_"%j; kn=(j==1)
    cell(p+"src","MOD %d source menu"%n,"Mod %d source"%n,None,0,chk=NT,known=kn)
    cell(p+"amt","MOD %d dest amount"%n,"Mod %d destination amount"%n,"Mod %d Dest Amount"%n,0,known=kn,chk=T("Mod 8 Dest Amount: -88"))
    cell(p+"d1","MOD %d dest 1 menu"%n,"Mod %d destination 1"%n,None,0,chk=NT,known=kn)
    cell(p+"amt1","MOD %d dest 2 amount"%n,"Mod %d destination 2 amount"%n,"Mod %d Dest 2 Amount"%n,0,known=kn,chk=T("Mod 8 Dest 2 Amount: 56"))
    cell(p+"d2","MOD %d dest 2 menu"%n,"Mod %d destination 2"%n,None,0,chk=NT,known=kn)
    cell(p+"amt2","MOD %d scale amount"%n,"Mod %d scale amount"%n,"Mod %d Scale Amount"%n,0,known=kn,chk=T("Mod 8 Scale Amount: 0"))
    cell(p+"scale","MOD %d scale menu"%n,"Mod %d scale source"%n,None,0,chk=NT,known=kn)
    cell(p+"clr","MOD %d clear"%n,"Clear mod row %d"%n,None,0,chk=T("Clear Sources, Modulations and Scales"),known=kn,typ="B")
for j in (1,2):
    n=11+j; p="mB%d_"%j; kn=(j==1)
    cell(p+"src","MOD %d source menu"%n,"Mod %d source"%n,None,0,chk=NT,known=kn)
    cell(p+"amt","MOD %d dest amount"%n,"Mod %d destination amount"%n,"Mod %d Dest Amount"%n,0,known=kn,chk=T("Mod 12 Dest Amount: 0"))
    cell(p+"dest","MOD %d dest menu"%n,"Mod %d destination"%n,None,0,chk=NT,known=kn)
    cell(p+"amt1","MOD %d scale amount"%n,"Mod %d scale 1 amount"%n,"Mod %d Scale Amount"%n,0,known=kn,chk=T("Mod 12 Scale Amount: 0"))
    cell(p+"s1","MOD %d scale 1 menu"%n,"Mod %d scale 1 source"%n,None,0,chk=NT,known=kn)
    cell(p+"amt2","MOD %d scale 2 amount"%n,"Mod %d scale 2 amount"%n,"Mod %d Scale 2 Amount"%n,0,known=kn,chk=T("Mod 12 Scale 2 Amount: 0"))
    cell(p+"s2","MOD %d scale 2 menu"%n,"Mod %d scale 2 source"%n,None,0,chk=NT,known=kn)
    cell(p+"clr","MOD %d clear"%n,"Clear mod row %d"%n,None,0,chk=T("Clear Sources, Modulations and Scales"),known=kn,typ="B")
# --- back: stitched picture = top (1269x952) over bottom scaled to width 1269
top=Image.open("_captures_batchE/thor_back_raw.jpg").convert("RGB"); bot=Image.open("_captures_batchE/thor_back_bottom_raw.jpg").convert("RGB")
s=top.width/bot.width; bot2=bot.resize((top.width,round(bot.height*s)))
st=Image.new("RGB",(top.width,top.height+bot2.height)); st.paste(top,(0,0)); st.paste(bot2,(0,top.height)); st.save("_captures_batchE/thor_back_stitched.jpg",quality=92)
B=[];CB={}
def b(label,what,typ,x,y,chk,hw=14,hh=14,why=""):
    B.append([label,what,typ,[x,y],[hw,hh],why]); CB[label]=T(chk)
def bt(label,what,typ,px,py,chk,**k): b(label,what,typ,round(px*s),round(top.height+py*s),chk,**k)
b("Mono Gate In","Gate input (mono)","J",146,58,"Mono Gate Input")
b("Mono CV In","CV input (mono pitch)","J",146,95,"Mono CV Input")
b("Pitch Bend trim","Amount for pitch bend CV","K",293,58,"Pitch Wheel Modulation Input: 127")
b("Pitch Bend CV In","CV input: pitch bend","J",326,58,"Pitch Wheel Modulation Input")
b("Mod Wheel trim","Amount for mod wheel CV","K",293,92,"Mod Wheel Modulation Input: 127")
b("Mod Wheel CV In","CV input: mod wheel","J",326,92,"Mod Wheel Modulation Input")
for i,(y,tn,kj,cn) in enumerate(((58,"Rotary 1","Rotary 1","Modulator 1"),(91,"Rotary 2","Rotary 2","Modulator 2"),(125,"Filter 1 Param X","Filter 1 Param X","Modulator 3"),(159,"Level","Level","Modulator 4")),1):
    lab={1:"Rotary 1",2:"Rotary 2",3:"Filter Freq",4:"Amp Level"}[i]
    b(lab+" trim","Amount for the %s CV input"%lab,"K",486,y,tn+": 127")
    b(lab+" CV In","CV input for %s"%lab,"J",519,y,kj)
    b("Mod Input CV %d"%i,"Modulation input CV %d (assignable modulation source)"%i,"J",595,y,cn)
b("Global Envelope Out","Global envelope CV output","J",722,58,"Global Envelope")
b("LFO 2 Out","LFO 2 CV output","J",722,92,"LFO 2")
for i,y in enumerate((58,92,126,160),1): b("Mod Output CV %d"%i,"Modulation output CV %d"%i,"J",800,y,"Modulator %d"%i)
for i,y in enumerate((58,92,126,160),1): b("Audio In %d"%i,"Audio input %d"%i,"J",939,y,"In %d"%i,hw=18,hh=18)
for i,(y,tn) in enumerate(((58,"Out 1 Left"),(92,"Out 2 Right"),(126,"Out 3"),(160,"Out 4")),1): b("Audio Out %d"%i,"Audio output %d"%i,"J",1118,y,tn,hw=18,hh=18)
bt("Seq Gate In","Step sequencer trigger input","J",270,99,"Step Sequencer Trig")
bt("Seq Rate trim","Amount for step sequencer rate CV","K",453,99,"Step Sequencer Rate: 127")
bt("Seq Rate In","Step sequencer rate CV input","J",497,99,"Step Sequencer Rate")
bt("Seq Pitch trim","Amount for step sequencer transpose CV","K",455,141,"Step Sequencer Transpose: 127")
bt("Seq Pitch In","Step sequencer pitch/transpose CV input","J",497,141,"Step Sequencer Transpose")
bt("Seq Gate Length trim","Amount for step sequencer gate length CV","K",695,99,"Step Sequencer Gate Length: 127")
bt("Seq Gate Length In","Step sequencer gate length CV input","J",737,99,"Step Sequencer Gate Length")
bt("Seq Velocity trim","Amount for step sequencer velocity CV","K",695,141,"Step Sequencer Velocity: 127")
bt("Seq Velocity In","Step sequencer velocity CV input","J",737,141,"Step Sequencer Velocity")
bt("Seq Note Out","Step sequencer note CV output","J",991,99,"Step Sequencer Note")
bt("Seq Curve 1 Out","Step sequencer curve 1 CV output","J",1148,99,"Step Sequencer Curve 1")
bt("Seq Start Out","Step sequencer start-of-sequence trigger output","J",1356,99,"Step Sequencer Start Trig")
bt("Seq Gate Out","Step sequencer gate/velocity output","J",991,141,"Step Sequencer Gate")
bt("Seq Curve 2 Out","Step sequencer curve 2 CV output","J",1148,141,"Step Sequencer Curve 2")
bt("Seq End Out","Step sequencer end-of-sequence trigger output","J",1356,141,"Step Sequencer End Trig")
# --- Filter 2 view (Filter 2 set to Low Pass Ladder; default patch has it on Bypass)
V=[];CV={}
def v(label,what,name,slot,x,y,typ,hw,hh,chk,conf="high",why=""):
    V.append([label,what,name,slot,[x,y],[hw,hh],typ,conf,why]); CV[label]=chk
v("FILTER 2 type menu","Filter 2 type (menu arrow)","Filter 2 Type",25,45,104,"D",16,12,NT,"medium","Remote 'Filter 2 Type' (slot 25); menu gave no tooltip; matched by meaning")
v("FILTER 2 power","Filter 2 on/off (close button)",None,None,512,113,"B",12,12,NT,"low")
v("FILTER 2 SELF OSC","Filter 2 self oscillation","Filter 2 Self Osc",None,368,145,"B",12,12,T("Filter 2 Self Osc"),why=NOSLOT)
for i,y in enumerate((181,205,229,254,280),1): v("FILTER 2 slope button %d"%i,"Filter 2 ladder slope selector %d"%i,None,None,360,y,"B",9,9,NT,"medium")
v("FILTER 2 FREQ","Filter 2 frequency","Filter 2 Freq",26,150,210,"K",52,52,T("Filter 2 Freq: 1.56 kHz"))
v("FILTER 2 RES","Filter 2 resonance","Filter 2 Res",27,265,208,"K",38,38,T("Filter 2 Res: 77"))
v("FILTER 2 DRIVE","Filter 2 drive","Filter 2 Drive",None,42,200,"S",16,70,T("Filter 2 Drive: 64"),why=NOSLOT)
v("FILTER 2 INV","Filter 2 envelope invert","Filter 2 Env Invert",None,43,316,"B",14,14,T("Filter 2 Env Invert"),why=NOSLOT)
v("FILTER 2 ENV","Filter 2 envelope amount","Filter 2 Env Amount",28,121,319,"K",34,34,T("Filter 2 Env Amount: 33"))
v("FILTER 2 VEL","Filter 2 velocity","Filter 2 Velocity",None,200,318,"K",34,34,T("Filter 2 Velocity: 47"),why=NOSLOT)
v("FILTER 2 KBD","Filter 2 keyboard tracking","Filter 2 Kbd",None,280,318,"K",34,34,T("Filter 2 Kbd: 0"),why=NOSLOT)
v("FILTER 2 slope selector","Filter 2 ladder slope",None,None,366,326,"B",18,16,T("Filter 2 Ladder Slope"),"medium","no Remote item")
base=dict(device="Thor Polysonic Synthesizer",prefix="THOR",remote_scope="Propellerheads / Thor Polysonic Synthesizer",date="2026-10-08",out_dir=".")
fr="_captures_batchE/thor_front_raw.jpg"
json.dump(dict(base,slug="thor",front_raw=fr,back_raw="_captures_batchE/thor_back_stitched.jpg",front=F,back=B),open("tools/specs/thor.json","w"))
json.dump(dict(device="Thor Polysonic Synthesizer",front=CF,back=CB),open("tools/checks/thor.json","w"),indent=0)
json.dump(dict(base,slug="thor-filter2-view",front_offsets={"K":500,"B":500,"D":500,"S":500},front_raw="_captures_batchE/thor_filter2_raw.jpg",back_raw="",front=V,back=[]),open("tools/specs/thor--filter2.json","w"))
ck=json.load(open("tools/checks/thor.json")); ck["views"]={"filter2":CV}; ck["view_titles"]={"filter2":"Filter 2 switched on (Low Pass Ladder; default patch has Bypass) (picture thor-filter2-view_front_labeled.png)"}
json.dump(ck,open("tools/checks/thor.json","w"),indent=0)
print(len(F),len(B),len(V))
