import json
F=[];B=[];CF={};CB={}
NT="no tooltip in Reason (hovered 1.3 s, approached from 5 px away)"
T=lambda s:'tooltip "%s"'%s
DUP="Remote item with a case-variant duplicate name; probably the same control as the row above; NOT proven"
def f(label,what,name,slot,x,y,hw,hh,typ,chk,conf="high",why=""):
    F.append([label,what,name,slot,[x,y],[hw,hh],typ,conf,why]); CF[label]=chk
def b(label,what,typ,x,y,hw,hh,chk,why=""):
    B.append([label,what,typ,[x,y],[hw,hh],why]); CB[label]=chk
f("Bypass/On/Off","3-way device switch","Enabled",4,115,38,12,22,"B",T("Enabled: On"))
f("(triangle)","Fold/unfold device",None,None,42,32,8,8,"B",NT,"medium")
f("Input meter","Input level lights",None,None,115,100,10,32,"D",NT)
f("FF logo","Powered by FF logo",None,None,243,103,30,28,"D",NT)
f("NEPTUNE 1 tape","Device name tape","Device Name",None,47,215,14,50,"D",T("Neptune 1")+" (device name)","medium","Remote item 'Device Name'; tooltip shows the rack name 'Neptune 1'")
f("LOW FREQ","Input: low-frequency mode","Low Freq Input",8,473,85,18,18,"B",T("Low Freq Input"))
f("WIDE VIBRATO","Input: wide vibrato","Wide Vibrato",25,473,131,18,18,"B",T("Wide Vibrato"))
f("LIVE MODE","Input: live mode","Live Mode",7,473,177,18,18,"B",T("Live Mode"))
f("MIDI","MIDI destination button (cycles between the three lights)","MIDI Destination",9,473,255,18,18,"B",T("MIDI Destination"))
f("MIDI (dup)","Remote duplicate of MIDI Destination (same button)","Midi Destination",10,455,255,6,6,"B","not hovered separately: same spot as MIDI; "+DUP,"low",DUP)
f("TO PITCH ADJUST","MIDI goes to Pitch Adjust (light)",None,None,473,301,12,12,"D",T("MIDI Destination"))
f("TO VOICE SYNTH","MIDI goes to Voice Synth (light)",None,None,473,347,12,12,"D",T("MIDI Destination"))
f("MIDI INPUT","MIDI input light",None,None,473,392,12,12,"D",NT)
f("BEND RANGE","Pitch bend range (stepper)","Pitch Bend Range",16,130,233,34,16,"D",T("Pitch Bend Range: 7"))
f("Pitch wheel","Pitch bend wheel","Pitch Bend",15,134,355,28,46,"S",T("Pitch Bend: 0"))
f("Pitch wheel (dup)","Remote duplicate 'pitch bend' (same wheel)","pitch bend",26,150,330,6,6,"S","not hovered separately: same wheel as Pitch wheel; "+DUP,"low",DUP)
f("Mod wheel","Mod wheel (vibrato wheel)","Mod Wheel",11,240,352,28,46,"S",T("Mod Wheel: 0"))
f("Mod wheel (dup)","Remote duplicate 'Mod wheel' (same wheel)","Mod wheel",12,255,330,6,6,"S","not hovered separately: same wheel as Mod wheel; "+DUP,"low",DUP)
f("VIBRATO RATE","Vibrato rate","Vibrato Rate",22,240,233,26,26,"K",T("Vibrato Rate: 64"))
f("VIBRATO RATE (dup)","Remote duplicate 'Vibrato rate' (same knob)","Vibrato rate",23,262,215,6,6,"K","not hovered separately: same knob as VIBRATO RATE; "+DUP,"low",DUP)
f("ROOT display","Root key display",None,None,564,134,26,16,"D",T("Root Key")+"; no Remote item")
f("ROOT stepper","Root key up/down",None,None,610,134,14,16,"B",T("Root Key")+"; no Remote item")
f("SCALE display","Scale name display",None,None,743,134,100,16,"D",T("Scale")+"; no Remote item")
f("SCALE stepper","Scale up/down",None,None,845,134,14,16,"B",T("Scale")+"; no Remote item")
for i,x in enumerate((895,930,965,1000)):
    f(f"SCALE MEMORY {i+1}",f"Scale memory slot {i+1}","Scale Memory",19 if i==0 else None,x,134,16,16,"B",T("Scale Memory"),"high" if i==0 else "medium","all four slots show tooltip 'Scale Memory'" if i else "")
f("CATCH ZONE SIZE","Catch zone slider (handle)","Catch Zone",1,771,188,14,14,"S",T("Catch Zone Size: 157")+" (Remote name is 'Catch Zone')")
f("Catch graph","Note catch display",None,None,785,242,250,26,"D",NT,"medium","display only")
for i,(n,x) in enumerate(zip(["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"],[563,603,643,681,719,758,797,837,877,915,957,995])):
    f(f"Key {n}",f"On-screen key {n} (note on/off for scale)",None,None,x,360,16,26,"B",NT,"medium","no tooltip; no Remote item")
f("PITCH ADJUST","Pitch adjust on/off","Pitch Adjust On/Off",14,1215,218,70,14,"B",T("Pitch Adjust On/Off"))
f("PITCH ADJUST amount?","Remote item 'Pitch Adjust Amount': panel control NOT found","Pitch Adjust Amount",13,1170,218,10,10,"B","not located: no panel control is known for this Remote item; row placed on the PITCH ADJUST button only so the checker has a position; NOT proven","low","Remote item with no known panel control; position is a placeholder")
f("CORRECTION SPEED","Correction speed","Correction Speed",3,1098,297,30,30,"K",T("Correction Speed: 64"))
f("PRESERVE EXPRESSION","Preserve expression","Preserve Expression",18,1204,297,30,30,"K",T("Preserve Expression: 0"))
f("TRANSPOSE","Transpose on/off","Transpose On/Off",21,1233,39,16,16,"B",T("Transpose On/Off"))
f("SEMI","Transpose semitones (stepper)","Semitones",20,1160,95,44,18,"D",T("Semitones: 0"))
f("CENT","Transpose cents (stepper)","Cent",2,1160,146,44,18,"D",T("Cents: 0")+" (Remote name is 'Cent')")
f("FORMANT","Formant on/off","Formant On/Off",5,1437,39,16,16,"B",T("Formant On/Off"))
f("SHIFT","Formant shift","Formant Shift",6,1365,105,26,26,"K",T("Formant Shift: 0"))
f("PITCHED SIGNAL","Mixer fader: pitched signal level","Pitched Signal Level",17,1328,248,14,14,"S","no tooltip on the handle or the rail (3 tries); name from the Remote list and the panel label","medium","name by label; NOT proven by tooltip")
f("VOICE SYNTH","Mixer fader: voice synth level","Voice Synth Level",24,1416,248,14,14,"S","no tooltip on the handle or the rail (3 tries); name from the Remote list and the panel label","medium","name by label; NOT proven by tooltip")
# back
b("(seq icon 1)","Sequencer control icon","D",63,48,14,18,NT)
b("(seq icon 2)","Sequencer control icon","D",63,98,14,18,NT)
b("Vent holes","Decoration","D",140,165,50,60,NT)
b("VOID IF REMOVED sticker","Decoration","D",1485,95,48,48,NT)
b("Note (Mono CV In)","Sequencer control: note CV input","J",100,385,18,18,T("Mono CV Input"))
b("Gate (Mono Gate In)","Sequencer control: gate input","J",205,385,18,18,T("Mono Gate Input"))
b("Bend trim","Amount for Bend CV","K",308,327,20,20,T("Pitch Bend Input: 127"),"trim above its CV jack; Remote has no item for it")
b("Vibrato trim","Amount for Vibrato CV","K",411,327,20,20,T("Mod Wheel Modulation Input: 127"),"trim above its CV jack; Remote has no item for it")
b("Formant trim","Amount for Formant CV","K",516,327,20,20,T("Formant Shift Input: 127"),"trim above its CV jack; Remote has no item for it")
b("Bend CV In","CV input: pitch bend","J",308,385,18,18,T("Pitch Bend Input"))
b("Vibrato CV In","CV input: vibrato (mod wheel)","J",411,385,18,18,T("Mod Wheel Modulation Input"))
b("Formant CV In","CV input: formant shift","J",516,385,18,18,T("Formant Shift Input"))
b("Pitch CV Out","CV output: pitch (after pitch adjuster/transpose)","J",640,385,18,18,T("Pitch Output"))
b("Amplitude CV Out","CV output: amplitude","J",743,385,18,18,T("Amplitude Output"))
b("Audio In L","Audio input left","J",877,383,20,20,T("Connected to Vocoder 1: Left Output")+"; this jack's own name NOT read yet")
b("Audio In R","Audio input right","J",948,383,20,20,T("Connected to Vocoder 1: Right Output")+"; this jack's own name NOT read yet")
b("Voice Synth Out L","Voice synth output left","J",1066,383,20,20,T("Voice Synth Left Output"))
b("Voice Synth Out R","Voice synth output right","J",1138,383,20,20,T("Voice Synth Right Output"))
b("Audio Out L","Audio output left","J",1255,383,20,20,'cabled: tooltip "Connected to Basic Pulverisation: Left Inp..." (cut off); own jack name NOT read yet')
b("Audio Out R","Audio output right","J",1327,383,20,20,'cabled: tooltip "Connected to Basic Pulverisation: Right In..." (cut off); own jack name NOT read yet')
base=dict(device="Neptune Pitch Adjuster",prefix="NEPT",remote_scope="Propellerheads / Neptune Pitch Adjuster",date="2026-10-07",out_dir=".")
json.dump(dict(base,slug="neptune",front_raw="_captures_batchD/neptune_front_raw.jpg",back_raw="_captures_batchD/neptune_back_raw.jpg",front=F,back=B),open("tools/specs/neptune.json","w"))
json.dump(dict(device="Neptune Pitch Adjuster",front=CF,back=CB),open("tools/checks/neptune.json","w"),indent=0)
print(len(F),len(B))
