import json
# NN19 Digital Sampler. One front picture, one back picture (same frame: screen=70+px/1.628, 62+py/1.628).
NT="no tooltip in Reason (hovered 1.5-2.5 s)"
T=lambda s:'tooltip "%s"'%s
NOSLOT="Remote item exists but is beyond the 48 knob slots of our remotemap (not mapped)"
notes={}; back={}; inback=False
for ln in open("_captures_batchE/nn19_notes.txt"):
    ln=ln.rstrip("\n")
    if ln=="BACK:": inback=True; continue
    p=ln.split("|",1)
    if len(p)==2: (back if inback else notes)[p[0]]=p[1]
def c(k,src=notes):
    v=src[k]
    return NT if v.startswith("(no tooltip") else T(v)
P=json.load(open("_captures_batchE/nn19_pts.json"))
K=1.628; OX,OY=70,62
rows=[]; chk={}
def f(key,label,what,typ,hw,hh,name=None,slot=None,conf="high",why="",pos=None,ck=None):
    sx,sy=pos or P[key]
    x=round((sx-OX)*K); y=round((sy-OY)*K)
    if name and slot is None and not why: why=NOSLOT
    rows.append([label,what,name,slot,[x,y],[round(hw*K),round(hh*K)],typ,conf,why])
    chk[label]=ck or c(key)
POS="matched by position/pattern"
f("fold","(triangle)","Fold/unfold device","B",8,8,conf="medium")
f("patchdisp","Patch display","Patch name display","D",70,12,conf="medium")
f("patcharrows","(patch arrows)","Previous / next patch","B",8,12,"Select Previous Patch",why="tooltip is for the upper half; lower half = Select Next Patch, not hovered")
f("patchfolder","(patch folder)","Browse patch","B",9,9)
f("patchdisk","(patch disk)","Save patch","B",9,9)
f("tape","Patch name tape","Patch name tape","D",8,40,"Device Name",conf="medium",why="Remote item 'Device Name'; tooltip shows the patch name; convention from earlier devices")
f("porta","PORTAMENTO","Portamento time","K",14,14,"Portamento",42)
f("poly","POLYPHONY display","Number of voices","D",16,10,"Polyphony",41,"medium","tooltip 'Polyphony'; Remote 'Polyphony' (slot 41)")
f("polyarrows","(polyphony arrows)","Voices down/up","B",7,12,conf="medium")
f("spread","SPREAD","Stereo spread","K",14,14,"Stereo Spread",48)
f("key","SPREAD MODE: KEY","Spread mode KEY","B",6,6)
f("key2","SPREAD MODE: KEY 2","Spread mode KEY 2","B",6,6)
f("jump","SPREAD MODE: JUMP","Spread mode JUMP","B",6,6)
f("spreadmode","SPREAD MODE button","Spread mode (steps KEY/KEY 2/JUMP)","B",10,7,"Spread Mode",47)
f("lobw","LO BW","Low bandwidth on/off","B",7,7,"Low Bandwidth On/Off",31)
f("noteon","NOTE ON light","Note-on indicator","D",5,5,"Note On Indicator",conf="medium",why="no tooltip; Remote item named Note On Indicator; "+NOSLOT)
f("legato","LEGATO","Key mode LEGATO light","B",6,6)
f("retrig","RETRIG","Key mode RETRIG light","B",6,6)
f("keymode","KEY MODE button","Key mode (steps LEGATO/RETRIG)","B",10,7,"Key Mode",24)
f("c_ffreq","CONTROLLER F.FREQ","Ext modulation to filter frequency","K",14,14,"Filter Freq Ext Mod")
f("c_lfo","CONTROLLER LFO","Ext modulation to LFO","K",14,14,"LFO Ext Mod")
f("c_amp","CONTROLLER AMP","Ext modulation to amp","K",14,14,"Amp Ext Mod")
f("atouch","A.TOUCH","Ext mod source: aftertouch","B",6,6)
f("expr","EXPR","Ext mod source: expression","B",6,6)
f("breath","BREATH","Ext mod source: breath","B",6,6)
f("source","SOURCE button","Choose ext mod source","B",10,7,"Ext Mod Select",8)
f("mw_ffreq","MOD WHEEL F.FREQ","Mod wheel to filter frequency","K",14,14,"Filter Freq Mod Wheel Amount",18)
f("mw_fres","MOD WHEEL F.RES","Mod wheel to filter resonance","K",14,14,"Filter Res Mod Wheel Amount")
f("mw_fdecay","MOD WHEEL F.DECAY","Mod wheel to filter decay","K",14,14,"Filter Decay Mod Wheel Amount")
f("mw_amp","MOD WHEEL AMP","Mod wheel to amp level","K",14,14,"Amp Mod Wheel Amount",6)
f("mw_lfo","MOD WHEEL LFO","Mod wheel to LFO amount","K",14,14,"LFO Mod Wheel Amount",27)
f("v_fenv","VELOCITY F.ENV","Velocity to filter envelope amount","K",14,14,"Filter Env Vel Amount",16)
f("v_fdecay","VELOCITY F.DECAY","Velocity to filter decay","K",14,14,"Filter Decay Vel Amount",9)
f("v_amp","VELOCITY AMP","Velocity to amp level","K",14,14,"Amp Vel Amount",7)
f("v_aatk","VELOCITY A.ATK","Velocity to amp attack","K",14,14,"Amp Attack Vel Amount",1)
f("v_sstart","VELOCITY S.START","Velocity to sample start","K",14,14,"Sample Start Vel Amount",45)
f("rangedisp","RANGE display","Pitch bend range","D",14,10,"Pitch Bend Range",40)
f("rangearrows","(range arrows)","Pitch bend range down/up","B",7,12,conf="medium")
f("wheelP","PITCH wheel","Pitch bend wheel","S",9,42,"Pitch Bend",39)
f("wheelM","MOD wheel","Mod wheel","S",9,42,"Mod Wheel",33)
f("midisel","SELECT KEYZONE VIA MIDI","Select keyzone by playing MIDI notes","B",7,7)
f("solo","SOLO SAMPLE","Solo sample","B",7,7,"Solo Sample",46)
f("topbtn1","(sample arrows)","Previous / next sample","B",12,12,why="tooltip 'Select previous sample' is for the upper half; lower half = next sample, not hovered")
f("topbtn2","(sample folder)","Browse sample","B",12,12)
f("topbtn3","(sample record)","Start sampling","B",12,12)
f("keymap","Keymap display","Keyboard map with sample zones","D",190,35,conf="medium")
f("lokey","LO KEY knob","Set sample low key","K",14,14)
f("hikey","HI KEY knob","Set sample high key","K",14,14)
f("sample","SAMPLE knob","Select sample","K",14,14,"Sample",43)
f("root","ROOT knob","Set sample root key","K",14,14)
f("tune","TUNE knob","Set sample tuning","K",14,14)
f("level","LEVEL knob","Set sample level","K",14,14)
f("loop","LOOP knob","Set sample loop mode","K",14,14)
f("sstart","SAMPLE START","Sample start offset","K",14,14,"Sample Start",44,"medium","tooltip 'Sample Start'; Remote 'Sample Start' (slot 44)")
f("oct","OCT","Oscillator octave","K",14,14,"Osc Octave",37)
f("semi","SEMI","Oscillator semitone","K",14,14,"Osc Semitone",38)
f("hqi","HIGH QUALITY INTERPOLATION","High quality interpolation on/off","B",7,7,"High Quality Interpolation",23)
f("envamt","ENV AMT","Oscillator envelope amount","K",14,14,"Osc Env Amount",34)
f("fine","FINE","Oscillator fine tune","K",14,14,"Osc Fine Tune",35)
f("kbdtrack","KBD TRACK","Oscillator keyboard tracking","B",7,7,"Osc Kbd Track",36)
f("lfosync","LFO SYNC","LFO tempo sync","B",8,8,"LFO Sync Enable",29)
f("lforate","LFO RATE","LFO rate","K",14,14,"LFO Rate",28)
f("lfoamt","LFO AMOUNT","LFO amount","K",14,14,"LFO Amount",25)
for i,l in enumerate(("triangle","inverted saw","saw","square","random","soft random")):
    f("wave%d"%(i+1),"LFO WAVE: "+l,"LFO waveform "+l,"B",6,6)
f("wavebtn","LFO WAVEF. button","LFO waveform (steps through)","B",10,7,"LFO Wave",30)
f("destosc","LFO DEST: OSC","LFO destination osc","B",6,6)
f("destfilter","LFO DEST: FILTER","LFO destination filter","B",6,6)
f("destpan","LFO DEST: PAN","LFO destination pan","B",6,6)
f("destbtn","LFO DEST button","LFO destination (steps OSC/FILTER/PAN)","B",10,7,"LFO Dest",26)
f("filtlight","FILTER on/off light","Filter on/off","B",8,8,"Filter On/Off",21)
f("filtfreq","FILTER FREQ slider","Filter frequency","S",6,40,"Filter Freq",17,"medium","no tooltip after 3 tries; Remote 'Filter Freq' (slot 17) matched by position")
f("filtres","FILTER RES slider","Filter resonance","S",6,40,"Filter Res",22)
f("fkbd","FILTER KBD","Filter keyboard tracking","K",14,14,"Filter Kbd Track",19)
for k,l in (("notch","NOTCH"),("hp24","HP 24"),("bp12","BP 12"),("lp12","LP 12"),("lp24","LP 24")):
    f("fm_"+k,"FILTER MODE: "+l,"Filter mode "+l,"B",6,6)
f("fmodebtn","FILTER MODE button","Filter mode (steps through)","B",10,7,"Filter Mode",20)
f("fenvA","FILTER ENV A","Filter envelope attack","S",6,30,"Filter Env Attack",11)
f("fenvD","FILTER ENV D","Filter envelope decay","S",6,30,"Filter Env Decay",12,"medium","no tooltip after 2 tries; Remote 'Filter Env Decay' matched by position in the A-D-S-R row")
f("fenvS","FILTER ENV S","Filter envelope sustain","S",6,30,"Filter Env Sustain",15)
f("fenvR","FILTER ENV R","Filter envelope release","S",6,30,"Filter Env Release",14,"medium","no tooltip after 2 tries; Remote 'Filter Env Release' matched by position in the A-D-S-R row")
f("finvert","FILTER ENV INVERT","Filter envelope invert","B",7,7,"Filter Env Invert",13)
f("fenvamt","FILTER ENV AMOUNT","Filter envelope amount","K",14,14,"Filter Env Amount",10)
f("alevel","AMP LEVEL slider","Amp level","S",6,35,why="no tooltip after 2 tries; no Remote item named Amp Level in the 48 slots (Master Level slot 32 is not on this panel)")
f("aenvA","AMP ENV A","Amp envelope attack","S",6,30,"Amp Env Attack",2)
f("aenvD","AMP ENV D","Amp envelope decay","S",6,30,"Amp Env Decay",3,"medium","no tooltip after 2 tries; Remote 'Amp Env Decay' matched by position in the A-D-S-R row")
f("aenvS","AMP ENV S","Amp envelope sustain","S",6,30,"Amp Env Sustain",5,"medium","no tooltip after 2 tries; Remote 'Amp Env Sustain' matched by position in the A-D-S-R row")
f("aenvR","AMP ENV R","Amp envelope release","S",6,30,"Amp Env Release",4)
f("alevel","(no panel control) Master Level","Remote item 'Master Level': no matching control on the NN19 panel","B",5,5,"Master Level",32,"low","Remote vocabulary item; NN19 has no master knob on the front; row parked on the AMP LEVEL slider; NOT proven",pos=(850,395),ck="not hovered: Remote item with no matching panel control")
B=[];CB={}
def b(key,label,what,typ,sx,sy,hw=11,hh=11):
    B.append([label,what,typ,[round((sx-OX)*K),round((sy-OY)*K)],[round(hw*K),round(hh*K)],""]); CB[label]=c(key,back)
b("gate","Seq Gate In","Gate input (sequencer)","J",175,159)
b("cv","Seq CV In","Note CV input (sequencer)","J",175,188)
for key,lab,y in (("pitch","Osc Pitch",159),("cutoff","Filter Cutoff",188),("res","Filter Res",217),("level","Level",247),("mw","Mod Wheel",276),("pw","Pitch Wheel",306)):
    b(key+"_trim",lab+" Mod trim","Amount for %s modulation input"%lab.lower(),"K",341,y,14,14)
    b(key+"_jack",lab+" Mod In","Modulation input: "+lab.lower(),"J",371,y)
b("fenv_out","Filter Env Mod Out","Modulation output: filter envelope","J",535,159)
b("lfo_out","LFO Mod Out","Modulation output: LFO","J",535,188)
b("ampgate","Amp Env Gate In","Gate input: amp envelope","J",701,159)
b("fgate","Filter Env Gate In","Gate input: filter envelope","J",701,188)
b("outL","Audio Out L","Audio output, left","J",873,173,14,14)
b("outR","Audio Out R","Audio output, right","J",919,173,14,14)
base=dict(device="NN19 Digital Sampler",prefix="NN19",remote_scope="Propellerheads / NN19 Digital Sampler",date="2026-10-08",out_dir=".")
json.dump(dict(base,slug="nn19",front_raw="_captures_batchE/nn19_front_raw.jpg",back_raw="_captures_batchE/nn19_back_raw.jpg",front=rows,back=B),open("tools/specs/nn19.json","w"))
json.dump(dict(device="NN19 Digital Sampler",front=chk,back=CB,views={},view_titles={}),open("tools/checks/nn19.json","w"),indent=0)
print(len(rows),len(B))
