import json
F=[];B=[];CF={};CB={}
NT="no tooltip in Reason (hovered 1.3 s, approached from 5 px away)"
T=lambda s:'tooltip "%s"'%s
def f(label,what,name,slot,x,y,hw,hh,typ,chk,conf="high",why=""):
    F.append([label,what,name,slot,[x,y],[hw,hh],typ,conf,why]); CF[label]=chk
def b(label,what,typ,x,y,hw,hh,chk,why=""):
    B.append([label,what,typ,[x,y],[hw,hh],why]); CB[label]=chk
f("(triangle)","Fold/unfold device",None,None,42,32,8,8,"B",NT,"medium")
f("Bypass/On/Off","3-way device switch","Enabled",3,90,28,12,22,"B",T("Enabled: On"))
f("(red light)","Red light next to the switch",None,None,203,33,18,18,"D",NT)
f("Patch display","Patch name display","Patch Name",None,808,33,100,16,"D",T("Basic Pulverisation"),"medium","Remote item 'Patch Name'; tooltip shows the patch name")
f("(up arrow)","Load previous patch","Select Previous Patch",None,1050,22,14,9,"B",T("Select previous patch"))
f("(down arrow)","Load next patch","Select Next Patch",None,1050,45,14,9,"B",T("Select next patch"))
f("(folder)","Open patch browser",None,None,1087,33,14,14,"B",T("Browse patch"))
f("(disk)","Save patch",None,None,1124,33,14,14,"B",T("Save patch"))
f("BASIC PULVER tape","Patch name tape","Device Name",None,75,215,14,60,"D",T("Basic Pulverisation")+" (patch name; 'Device Name' item not provable here)","medium","Remote item 'Device Name'; convention from earlier devices")
f("SQUASH","Squash (compression) amount","Squash",16,168,152,52,52,"K",T("Squash: 49%"))
f("DIRT","Dirt (distortion) amount","Dirt",2,321,152,52,52,"K",T("Dirt: 61%"))
f("RELEASE","Squash release time","Release",14,165,282,32,32,"K",T("Release: 56%"))
f("TONE","Tone","Tone",18,321,282,32,32,"K",T("Tone: 83%"))
f("Filter mode","Filter mode lever (Bypass / Low Pass 24 / LP12+Notch / Band Pass / High Pass / Comb)","Filter Mode",5,610,180,28,30,"S",T("Filter Mode: Low Pass 24"))
f("FREQUENCY","Filter frequency","Filter Frequency",4,481,320,50,50,"K",T("Filter Frequency: 11.05 kHz"))
f("PEAK","Filter peak (resonance)","Peak",13,615,320,50,50,"K",T("Peak: 14%"))
f("Routing","Order of Squash, Dirt and Filter","Routing",15,360,372,30,16,"S",T("Routing: 1"))
f("Tremor RATE","Tremor rate","Tremor Rate",20,855,145,32,32,"K",T("Tremor Rate: 1.68 Hz"))
f("Tremor SYNC light","Tremor sync light",None,None,935,118,18,18,"D",NT)
f("Tremor SYNC","Tremor tempo sync","Sync",17,933,167,18,18,"B",T("Tremor Sync")+" (Remote name is 'Sync')")
f("Tremor WAVEFORM","Tremor waveform display (pick a shape with the arrows)","Tremor Waveform",22,1020,145,34,30,"D",T("Tremor Waveform: Sine"))
f("Waveform up arrow","Previous waveform",None,None,1085,130,14,10,"B",NT)
f("Waveform down arrow","Next waveform",None,None,1085,160,14,10,"B",NT)
f("Tremor SPREAD light","Tremor spread light",None,None,1160,118,18,18,"D",NT)
f("Tremor SPREAD","Tremor stereo spread on/off","Tremor Spread",21,1158,167,18,18,"B",T("Tremor Spread"))
f("Tremor LAG","Tremor lag","Tremor Lag",19,1236,150,20,20,"K",T("Tremor Lag: 16%"))
f("Tremor > Frequency","Tremor amount to filter frequency","Tremor to Frequency",23,755,150,22,22,"K",T("Tremor to Frequency: 0%"))
f("Follower > Rate","Follower amount to tremor rate","Follower to Rate",12,755,247,22,22,"K",T("Follower to Rate: 0%"))
f("Follower > Frequency","Follower amount to filter frequency","Follower to Frequency",11,755,350,22,22,"K",T("Follower to Frequency: 0%"))
f("Tremor > Volume","Tremor amount to volume","Tremor to Volume",24,1327,152,22,22,"K",T("Tremor to Volume: 0%"))
f("VOLUME","Output volume","Volume",25,1432,148,52,52,"K",T("Volume: 65%"))
f("BLEND","Dry/wet blend","Blend",1,1390,318,52,52,"K",T("Blend: 100%"))
f("Follower TRIG","Follower trigger button","Follower Trig",10,856,348,18,18,"B",T("Follower Trig"))
f("THRESHOLD","Follower threshold","Follower Threshold",9,937,345,32,32,"K",T("Follower Threshold: 0%"))
f("Follower light","Follower light (red)","Follow",6,1028,345,18,18,"D","no tooltip; Remote item 'Follow' is a 'flat' item (did not change during the sweep); placed on this light, NOT proven","low","Remote item 'Follow'; likely this lamp; NOT proven")
f("ATTACK","Follower attack","Follower Attack",7,1107,345,32,32,"K",T("Follower Attack: 0%"))
f("Follower RELEASE","Follower release","Follower Release",8,1197,345,32,32,"K",T("Follower Release: 0%"))
b("BASIC PULVER tape (back)","Patch name tape (back)","D",133,238,14,60,T("Basic Pulverisation"))
b("(routing icon 1)","Routing icon","D",170,188,14,18,NT)
b("(routing icon 2)","Routing icon","D",170,228,14,18,NT)
b("(triangle) back","Fold/unfold device","D",58,32,8,8,NT)
for i,(lab,tt,tj,y,yj) in enumerate((("Squash","Squash CV Modulation Amount: 100%","Squash CV In",111,113),("Dirt","Dirt CV Modulation Amount: 100%","Dirt CV In",162,164),("Filter Frequency","Filter Freq CV Modulation Amount: 100%","Filter CV In",215,216),("Tremor Rate","Tremor Rate CV Modulation Amount: 100%","Tremor CV In",266,267),("Volume","Volume CV Modulation Amount: 100%","Volume CV In",317,318))):
    b(f"{lab} CV trim",f"Amount for {lab} CV","K",237,y,20,20,T(tt),"trim next to CV jack; Remote has no item for it")
    b(f"{lab} CV In",f"CV input: {lab}","J",283,yj,18,18,T(tj))
b("Filter Frequency audio trim","Amount for Filter Frequency audio modulation","K",514,111,20,20,T("Filter Freq Audio Modulation Amount: 100%"),"trim next to audio jack; Remote has no item for it")
b("Filter Frequency audio In","Audio modulation input: Filter Frequency","J",563,113,20,20,T("Filter Freq Audio Modulation In"))
b("Volume audio trim","Amount for Volume audio modulation","K",514,162,20,20,T("Volume Audio Modulation Amount: 100%"),"trim next to audio jack; Remote has no item for it")
b("Volume audio In","Audio modulation input: Volume","J",563,164,20,20,T("Volume Audio Modulation In"))
b("Follower CV trim","Amount for Follower CV","K",518,317,20,20,T("Follower CV Modulation Amount: 100%"),"trim next to CV jack; Remote has no item for it")
b("Follower CV In","CV input: Follower (breaks internal routing)","J",564,317,18,18,T("Follow CV In"))
b("Follower mod Out","Modulation output: Follower","J",826,117,18,18,T("Follower CV Out"))
b("Tremor mod Out","Modulation output: Tremor","J",826,167,18,18,T("Tremor CV Out"))
b("Audio In L","Audio input left","J",1238,133,20,20,T("Connected to Neptune 1: Left Output")+"; this jack's own name NOT read yet")
b("Audio In R","Audio input right","J",1307,133,20,20,T("Connected to Neptune 1: Right Output")+"; this jack's own name NOT read yet")
b("Audio Out L","Audio output left","J",1238,275,20,20,'cabled: tooltip "Connected to Big BBD Ensemble: Left Inpu(t)" (cut off); own jack name NOT read yet')
b("Audio Out R","Audio output right","J",1307,275,20,20,'cabled: tooltip "Connected to Big BBD Ensemble: Right Inp(ut)" (cut off); own jack name NOT read yet')
b("Warning plate","Warning plate (decoration)","D",868,338,130,55,NT)
b("PULVERISER logo","Logo (decoration)","D",1060,190,65,55,NT)
base=dict(device="Pulveriser",prefix="PULV",remote_scope="Propellerheads / Pulveriser",date="2026-10-07",out_dir=".")
json.dump(dict(base,slug="pulveriser",front_raw="_captures_batchD/pulveriser_front_raw.jpg",back_raw="_captures_batchD/pulveriser_back_raw.jpg",front=F,back=B),open("tools/specs/pulveriser.json","w"))
json.dump(dict(device="Pulveriser",front=CF,back=CB),open("tools/checks/pulveriser.json","w"),indent=0)
print(len(F),len(B))
