import json
# Mimic Creative Sampler. Front picture 1288x930 (zoom of screen 72..1028 x 110..800), back 1232x977. Notes: _captures_batchE/mimic_front_notes.txt, mimic_hover_notes.txt
NT="no tooltip in Reason (hovered 1.3 s, approached from 5 px away)"
T=lambda s:'tooltip "%s"'%s
NOSLOT="Remote item exists in Reason but is beyond the 48 knob slots of our remotemap (not mapped)"
SEL="Remote has Slot 1-8 versions; this one physical control acts on the SELECTED slot (slot 1 when checked)"
notes={}
for ln in open("_captures_batchE/mimic_front_notes.txt"):
    p=ln.rstrip("\n").split("|",2)
    if len(p)==3: notes[p[1]]=p[2]
bn={}
for ln in open("_captures_batchE/mimic_hover_notes.txt"):
    p=ln.rstrip("\n").split("|",2)
    if len(p)==3: bn[p[1]]=p[2]
pts={a:(x,y) for a,x,y in json.load(open("_captures_batchE/mimic_pts.json"))}
bpts={a:(x,y) for a,x,y in json.load(open("_captures_batchE/mimic_back_pts.json"))}
def c(k,src=notes):
    v=src[k]
    if v.startswith("(no tooltip"): return NT if "first try" not in v else NT+"; retried 2 s, still none"
    return T(v)
F=[];CF={};B=[];CB={}
def f(label,what,name,slot,key,hw,hh,typ,conf="high",why="",mode=None,chk=None):
    x,y=pts[key]
    F.append([label,what,name,slot,[x,y],[hw,hh],typ,conf,why]+([mode] if mode else [])); CF[label]=chk or c(key)
f("(triangle)","Fold/unfold device",None,None,"fold",8,8,"B","medium")
f("(red light)","Note-on light",None,None,"light",8,8,"D","low","Remote has a Note On Indicator item only on other devices; this light gave no tooltip")
f("Patch display","Patch name display","Patch Name",None,"patchdisp",150,16,"D","medium","Remote item 'Patch Name'; display gave no tooltip; NOT proven")
f("(patch arrows)","Previous / next patch","Select Previous Patch",None,"patchstep",12,14,"B",chk=T("Select previous patch")+" (upper half; lower half = Select Next Patch, not hovered)")
f("(patch folder)","Open patch browser",None,None,"patchfolder",13,12,"B")
f("(patch disk)","Save patch",None,None,"patchdisk",13,12,"B")
f("BASIC VIBE tape","Patch name tape","Device Name",None,"tape",50,12,"D","medium","Remote item 'Device Name'; convention from earlier devices")
f("MASTER VOLUME","Master volume","Master Volume",41,"MASTER",40,40,"K")
f("MODE: Pitch","Play mode: Pitch","Play Mode",42,"modePitch",42,32,"B","medium","Remote item 'Play Mode' (slot 42) steps through the 4 mode buttons; button gave no tooltip",chk=NT,mode="in")
f("MODE: Slice","Play mode: Slice",None,None,"modeSlice",42,32,"B","medium",chk=NT,mode="in")
f("MODE: Multi Slot","Play mode: Multi Slot",None,None,"modeMulti",42,32,"B","medium",chk=NT,mode="in")
f("MODE: Multi Pitch","Play mode: Multi Pitch",None,None,"modeMultiPitch",42,32,"B","medium",chk=NT,mode="in")
for n in range(1,9):
    f(f"SLOT {n} tab",f"Select sample slot {n}",None,None,f"slot{n}",30,14,"B","medium",chk=NT,mode="in")
f("Overview waveform","Whole-sample overview with start/end markers",None,None,"overview",420,18,"D")
f("ANALYZED","Analysed pitch of the sample",None,None,"analyzed",36,10,"D")
f("SET","Set root note from analysis",None,None,"SET",20,10,"B")
f("ROOT note","Root note",None,None,"rootnote",24,12,"D")
f("TUNE display","Root fine tune",None,None,"tune",20,12,"D")
f("Main waveform","Waveform: sets start, end, loop and slices",None,None,"waveform",600,100,"D",why="start/end/loop are set by double-click in the waveform (see the Shortcuts list on the back)")
f("START marker","Sample start marker","Start Pos 1",4,"startmark",8,8,"B","low",SEL+". Marker gave no tooltip; Remote 'Start Pos 1' (slot 4) matched by meaning, NOT proven")
f("END marker","Sample end marker",None,None,"endmark",8,8,"B","medium",chk=NT)
f("(sample arrows)","Previous / next sample",None,None,"loadstep",11,14,"B",chk=T("Select previous sample")+" (upper half; lower half not hovered)")
f("(sample folder)","Browse samples",None,None,"folder",11,10,"B")
f("(sample button)","Start sampling",None,None,"sample",11,10,"B")
f("Sample name display","Name of the loaded sample",None,None,"filename",90,14,"D")
f("CLR","Delete the sample from the slot",None,None,"CLR",10,10,"B")
f("LOOP","Loop on/off","Loop On 1",None,"LOOP",8,8,"B",why=SEL+". "+NOSLOT)
f("LOOP LENGTH","Loop length","Loop Length 1",None,"LENGTH",12,12,"K",why=SEL+". "+NOSLOT)
f("Keyboard","Keyboard: shows root note and range",None,None,"keyboard",230,12,"D")
f("GLOBAL POSITION","Global start position","Global Pos 1",None,"globalpos",8,8,"B",why=SEL+". "+NOSLOT)
f("SNAP TO SLICES","Snap start to slices","Snap Slices 1",None,"snap",8,8,"B",why=SEL+". "+NOSLOT)
f("REVERSE","Reverse the sample","Reverse 1",None,"reverse",8,8,"B",why=SEL+". "+NOSLOT)
f("START MOD amount","Start position: mod amount",None,None,"startmod",11,11,"K",why=SEL+". "+NOSLOT)
f("START MOD source","Start position: mod source menu","Start Mod 1",None,"startdest",36,8,"D","medium",chk=NT,why="menu showing 'Off'; Remote 'Start Mod 1' matched by meaning, NOT proven. "+NOSLOT)
f("SPEED","Stretch speed","Stretch Speed 1",None,"speed",22,22,"K",why=SEL+". "+NOSLOT)
f("SPEED MOD amount","Speed: mod amount","Speed ModAmt 1",None,"speedmod",11,11,"K",why=SEL+". "+NOSLOT)
f("SPEED MOD source","Speed: mod source menu","Speed Mod 1",None,"speeddest",36,8,"D","medium",chk=NT,why="menu showing 'Off'; matched by meaning, NOT proven. "+NOSLOT)
f("STRETCH mode menu","Stretch algorithm menu (Tape / ...)","Algorithm",43,"stretchmenu",44,12,"D","low",chk=NT,why="Remote 'Algorithm' (slot 43) and 'Stretch Mode 1' both exist; NOT proven which one this menu is")
f("LOOP X-FADE","Loop crossfade","Loop Xfade 1",None,"loopxfade",14,14,"K","medium",chk=NT+" (knob; label LOOP X-FADE shows 50%)",why=SEL+". "+NOSLOT)
f("SLICES RESET","Reset slices",None,None,"slicesreset",30,10,"B","medium",chk=NT)
f("PLAY THRU","Play-through for slices","Play Thru 1",None,"playthru",8,8,"B",why=SEL+". "+NOSLOT)
f("SLICES SENSITIVITY","Slice detection sensitivity","Slice Sens 1",None,"sens",20,20,"K",why=SEL+". "+NOSLOT)
f("PORTA knob","Portamento rate","Portamento Rate 1",None,"porta",14,14,"K",why=SEL+". "+NOSLOT)
f("PORTA switch (OFF/ON/AUTO)","Portamento mode","Portamento Mode 1",None,"portaswitch",10,24,"B",why=SEL+". "+NOSLOT)
f("POLY","Key mode: poly","Key Mode 1",None,"poly",8,8,"B",why="all three key-mode buttons show 'Key Mode 1'. "+NOSLOT)
f("MONO RETRIG","Key mode: mono retrig",None,None,"monoretrig",8,8,"B")
f("MONO LEGATO","Key mode: mono legato",None,None,"monolegato",8,8,"B")
f("PITCH KBD","Pitch follows keyboard","Pitch Kbd 1",None,"kbd",16,12,"B",why=SEL+". "+NOSLOT)
f("PITCH SEMI","Pitch in semitones","Pitch Semi 1",2,"semi",26,26,"K",why=SEL)
f("Semi display","Semitone readout",None,None,"semidisp",24,16,"D",chk=NT)
f("PITCH TUNE","Fine tune","Tune 1",None,"tuneK",16,16,"K",why=SEL+". "+NOSLOT)
f("PITCH LFO","Pitch LFO amount",None,None,"lfoK",12,12,"K",why=SEL+". "+NOSLOT)
f("PITCH MOD amount","Pitch mod amount",None,None,"pmodK",12,12,"K",why=SEL+". "+NOSLOT)
f("PITCH MOD source","Pitch: mod source menu","Pitch Mod 1",None,"pdest",36,8,"D","medium",chk=NT,why="menu showing 'Off'; matched by meaning, NOT proven. "+NOSLOT)
f("PITCH RANGE","Pitch bend range","Pitchbend Range 1",None,"pbrange",12,12,"K",why=SEL+". "+NOSLOT)
f("LFO SCALE","Mod wheel to LFO amount",None,None,"lfoscale",12,12,"K",chk=T("MW LFO 1: 0.0 %"),why="tooltip name 'MW LFO 1'; not a Remote item")
f("PITCH wheel","Pitch bend wheel",None,None,"wheelP",12,48,"S",chk=NT+"; Remote item 'Pitch Bend' matched by label, NOT proven",why="Remote item 'Pitch Bend'; no knob slot")
f("MOD wheel","Mod wheel",None,None,"wheelM",12,48,"S",chk=NT+"; Remote item 'Mod Wheel' matched by label, NOT proven",why="Remote item 'Mod Wheel'; no knob slot")
f("FILTER type menu","Filter type menu","Filter Type 1",None,"ftype",60,10,"D","medium",chk=NT,why="menu showing 'Off'; matched by meaning, NOT proven. "+NOSLOT)
f("(filter light)","Filter indicator light",None,None,"fled",12,6,"D",chk=NT)
f("FILTER FREQ","Filter frequency","Filter Freq 1",3,"freq",26,26,"K",why=SEL)
f("FILTER RESO","Filter resonance","Filter Reso 1",None,"reso",16,16,"K",why=SEL+". "+NOSLOT)
f("FILTER DRIVE","Filter drive","Filter Drive 1",None,"drive",20,20,"K",why=SEL+". "+NOSLOT)
f("FILTER KBD","Filter key tracking",None,None,"fkbd",12,12,"K",why=SEL+". "+NOSLOT)
f("FILTER VEL","Filter velocity",None,None,"fvel",12,12,"K",chk=T("Filter Vel 1: 0.0 %"),why="tooltip name 'Filter Vel 1'; no such Remote item. "+SEL)
f("FILTER ENV","Filter envelope amount","Filter Env 1",None,"fenv",12,12,"K",why=SEL+". "+NOSLOT)
f("FILTER MOD amount","Filter mod amount","Filter ModAmt 1",None,"fmod",12,12,"K",why=SEL+". "+NOSLOT)
f("FILTER MOD source","Filter: mod source menu","Filter Mod 1",None,"fdest",36,8,"D","medium",chk=NT,why="menu showing 'Off'; matched by meaning, NOT proven. "+NOSLOT)
f("FILTER ENV A","Filter envelope attack","Filter Attack 1",None,"fenvA",8,26,"S",why=SEL+". "+NOSLOT)
f("FILTER ENV D","Filter envelope decay","Filter Decay 1",None,"fenvD",8,26,"S","medium",chk=NT+"; retried 2 s, still none",why=SEL+". "+NOSLOT)
f("FILTER ENV S","Filter envelope sustain","Filter Sustain 1",None,"fenvS",8,26,"S","medium",chk=NT+"; retried 2 s, still none",why=SEL+". "+NOSLOT)
f("FILTER ENV R","Filter envelope release","Filter Release 1",None,"fenvR",8,26,"S",why=SEL+". "+NOSLOT)
f("AMP ENV A","Amp envelope attack","Amp Attack 1",None,"aenvA",8,26,"S",why=SEL+". "+NOSLOT)
f("AMP ENV D","Amp envelope decay","Amp Decay 1",5,"aenvD",8,26,"S","medium",chk=NT+"; retried 2 s, still none",why=SEL)
f("AMP ENV S","Amp envelope sustain","Amp Sustain 1",None,"aenvS",8,26,"S","medium",chk=NT+"; retried 2 s, still none",why=SEL+". "+NOSLOT)
f("AMP ENV R","Amp envelope release","Amp Release 1",None,"aenvR",8,26,"S",why=SEL+". "+NOSLOT)
f("LFO WAVE display","LFO waveform","LFO Wave 1",None,"lfowave",34,22,"D","medium",chk=NT,why="Remote 'LFO Wave 1' matched by label, NOT proven. "+NOSLOT)
f("LFO WAVE arrows","Previous / next LFO wave",None,None,"lfowavearrow",8,16,"B","medium",chk=NT)
f("KEY SYNC","LFO key sync","LFO Key Sync 1",None,"keysync",8,8,"B",why=SEL+". "+NOSLOT)
f("BEAT SYNC","LFO beat sync","LFO Beat Sync 1",None,"beatsync",8,8,"B",why=SEL+". "+NOSLOT)
f("LFO RATE","LFO rate","LFO Rate 1",None,"lforate",20,20,"K",why=SEL+". "+NOSLOT)
f("LFO DELAY","LFO delay","LFO Delay 1",None,"lfodelay",18,18,"K",why=SEL+". "+NOSLOT)
f("AMP VEL","Amp velocity amount","Amp Velocity 1",None,"avel",12,12,"K",why=SEL+". "+NOSLOT)
f("AMP GAIN","Amp gain","Amp Gain 1",1,"again",24,24,"K",why=SEL)
f("AMP MOD amount","Amp mod amount","Amp ModAmt 1",None,"amod",12,12,"K",why=SEL+". "+NOSLOT)
f("AMP MOD source","Amp: mod source menu","Amp Mod 1",None,"adest",48,8,"D","medium",chk=NT,why="menu showing 'Off'; matched by meaning, NOT proven. "+NOSLOT)
f("PAN","Pan","Pan 1",None,"pan",18,18,"K",why=SEL+". "+NOSLOT)
f("PAN MOD amount","Pan mod amount",None,None,"panmod",12,12,"K",why=SEL+". "+NOSLOT)
f("PAN MOD source","Pan: mod source menu","Pan Mod 1",None,"pandest",48,8,"D","medium",chk=NT,why="menu showing 'Off'; matched by meaning, NOT proven. "+NOSLOT)
f("COMP light","Compressor indicator","Squeeze 1",None,"comp",12,10,"D","low",chk=T("Squeeze 1: 0.0 %")+" (shown on the Comp section's light)",why=SEL+". Same Remote item as SQUEEZE; NOT separately proven. "+NOSLOT)
f("SQUEEZE","Compressor squeeze","Squeeze 1",None,"squeeze",16,16,"K",why=SEL+". "+NOSLOT)
f("EFFECT type menu","Effect type menu (Noise ...)","Effect Type 1",None,"effectmenu",44,10,"D","medium",chk=NT,why="menu; Remote 'Effect Type 1' matched by meaning, NOT proven. "+NOSLOT)
f("EFFECT dots","Effect display",None,None,"effectdots",20,12,"D",chk=T("Effect Type 1: Noise"),why="tooltip name 'Effect Type 1: Noise'; this is the effect picture, not the menu")
f("EFFECT MOD","Effect modulation","Effect Mod 1",None,"effectmod",24,24,"K",why=SEL+". "+NOSLOT)
f("EFFECT MIX","Effect mix","Effect Mix 1",None,"mix",14,14,"K",why=SEL+". "+NOSLOT)
f("LO CUT","Low cut","Lo Cut 1",None,"locut",16,16,"K",why=SEL+". "+NOSLOT)
f("HI CUT","High cut","Hi Cut 1",None,"hicut",16,16,"K",why=SEL+". "+NOSLOT)
f("SEND 1","Send 1 level","Send1 1",None,"send1",16,16,"K",chk=T("Send1 1: -∞ dB"),why=SEL+". Remote name is 'Send1 1' (slot 1, send 1). "+NOSLOT)
f("SEND 2","Send 2 level",None,None,"send2",16,16,"K",chk=T("Send2 1: -∞ dB"),why=SEL+". Remote name is 'Send2 1'. "+NOSLOT)
def b(label,what,typ,key,hw,hh,why=""):
    x,y=bpts[key]; B.append([label,what,typ,[x*1232/880*0+round((x-112)*1232/880),round((y-110)*1232/880)],[hw,hh],why]); CB[label]=T(bn[key]) if not bn[key].startswith("(no") else NT
# back points are screen px of the full back zoom (112..992 x 110..808, scale 1.4)
# NOTE: bpts were defined in back-picture px, so no remapping needed
B.clear(); CB.clear()
def b(label,what,typ,key,hw,hh,why=""):
    x,y=bpts[key]; B.append([label,what,typ,[x,y],[hw,hh],why]); CB[label]=NT if bn[key].startswith("(no") else T(bn[key])
b("BASIC VIBE tape (back)","Patch name tape (back)","D","tape",50,14)
b("Seq Gate In","Gate input from a sequencer","J","gate",14,14)
b("Seq Note CV In","Note CV input from a sequencer","J","cv",14,14)
b("Pitch Bend CV trim","Amount for pitch bend CV","K","pbK",14,14,"trim next to CV jack; no Remote item")
b("Pitch Bend CV In","CV input: pitch bend","J","pbJ",14,14)
b("Mod Wheel CV trim","Amount for mod wheel CV","K","mwK",14,14,"trim next to CV jack; no Remote item")
b("Mod Wheel CV In","CV input: mod wheel","J","mwJ",14,14)
for i in (1,2,3,4): b(f"CV In {i}","CV input %d (assignable as a modulation source)"%i,"J",f"cv{i}",14,14)
for i in range(1,9):
    b(f"Slot {i} Out L",f"Audio output slot {i}, left","J",f"s{i}L",16,16)
    b(f"Slot {i} Out R",f"Audio output slot {i}, right","J",f"s{i}R",16,16)
for i in (1,2):
    b(f"FX Send {i} L",f"FX send {i} output, left","J",f"fx{i}L",18,18)
    b(f"FX Send {i} R",f"FX send {i} output, right","J",f"fx{i}R",18,18)
b("Master Out L","Master audio output, left","J","mL",18,18,"tooltip says 'Left Output'")
b("Master Out R","Master audio output, right","J","mR",18,18,"tooltip says 'Right Output'")
base=dict(device="Mimic",prefix="MIMC",remote_scope="Propellerheads / Mimic",date="2026-10-08",out_dir=".")
json.dump(dict(base,slug="mimic",front_raw="_captures_batchE/mimic_front_raw.jpg",back_raw="_captures_batchE/mimic_back_raw.jpg",front=F,back=B),open("tools/specs/mimic.json","w"))
json.dump(dict(device="Mimic",front=CF,back=CB),open("tools/checks/mimic.json","w"),indent=0)
print(len(F),len(B))
