#!/usr/bin/env python3
"""Build the Reason Remote vocabulary from Reason's own factory mapping files.

Reason 12 ships no manual, but it does ship the Remote data for every control
surface it supports. Those .remotemap files name the parameters that factory
control surfaces map, spelled exactly the way Reason spells it. That spelling is
the whole point: a remotable item name that is even slightly wrong fails
SILENTLY -- Reason does not complain, the knob just never moves.

This is a LOWER BOUND on what Reason accepts, not a complete list: a device can
expose parameters no factory surface happens to map (Mimic's Voice Formant 2-8,
for one). Never use absence from this output as proof a parameter doesn't exist.

So we never type these names by hand. We read them out of Reason.

    python3 tools/reason_vocab.py            # writes docs/reason/remote-vocab.json
    python3 tools/reason_vocab.py --device "MClass Compressor"

Re-run it after a Reason update; the file is a snapshot, not a fixed truth.
"""
from __future__ import annotations

import argparse
import json
import plistlib
import re
from collections import defaultdict
from datetime import date
from pathlib import Path

APP = Path("/Applications/Reason 12.app")
MAPS = APP / "Contents/Resources/Remote"
OUT = Path(__file__).parent.parent / "docs/reason/remote-vocab.json"

# Rack Extension / Reason-12 device scopes are reverse-DNS ids, not names.
RE_ID = re.compile(r"^[a-z]+\.[a-z]+\.(.+)$", re.I)

# A remotemap's "remotable item" column is not always a parameter. Per Reason's
# own error strings (Resources/RemoteStrings.txt) it may also hold a text
# constant, a numeric constant, or a group assignment -- all of which drive the
# surface's own display or mapping variations, not a knob in the rack.
GROUP_ASSIGNMENT = re.compile(r"^[^=]+=[^=]*$")


def is_parameter(item: str) -> bool:
    """False for text constants ("Thresh"), numbers, and Group=Value entries."""
    if not item or item.startswith('"') or item.endswith('"'):
        return False
    if GROUP_ASSIGNMENT.match(item):
        return False
    return not item.lstrip("-").replace(".", "", 1).isdigit()


def display_name(scope_model: str) -> str:
    """'se.propellerheads.Mimic' -> 'Mimic'; plain names pass through."""
    m = RE_ID.match(scope_model)
    return m.group(1) if m else scope_model


def reason_version() -> str:
    try:
        plist = plistlib.loads((APP / "Contents/Info.plist").read_bytes())
        return plist.get("CFBundleShortVersionString", "unknown")
    except Exception:
        return "unknown"


def parse_map(path: Path):
    """Yield (manufacturer, model, remotable_item) from one .remotemap.

    Format is TAB-separated:
        Scope <tab> Manufacturer <tab> Model
        Map   <tab> Surface Item <tab> Key <tab> Remotable Item <tab> Scale <tab> Mode
    """
    manufacturer = model = None
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        cols = line.split("\t")
        if cols[0] == "Scope" and len(cols) >= 3:
            manufacturer, model = cols[1].strip(), cols[2].strip()
        elif cols[0] == "Map" and model and len(cols) >= 4:
            item = cols[3].strip()
            if is_parameter(item):
                yield manufacturer, model, item


def build() -> dict:
    devices: dict[str, dict] = {}
    items: dict[str, set] = defaultdict(set)
    files = sorted(MAPS.rglob("*.remotemap"))
    if not files:
        raise SystemExit(f"No .remotemap files under {MAPS} — is Reason 12 installed?")
    for f in files:
        for manufacturer, model, item in parse_map(f):
            devices.setdefault(model, {"manufacturer": manufacturer,
                                       "name": display_name(model)})
            items[model].add(item)
    for model, meta in devices.items():
        meta["items"] = sorted(items[model])
    return {
        "_comment": "Generated by tools/reason_vocab.py -- do not hand-edit. "
                    "Item names are copied verbatim from Reason's factory maps; "
                    "a wrong name fails silently.",
        "generated": date.today().isoformat(),
        "reason_version": reason_version(),
        "source": str(MAPS),
        "source_files": len(files),
        "device_count": len(devices),
        "item_count": sum(len(v) for v in items.values()),
        "devices": dict(sorted(devices.items(), key=lambda kv: kv[1]["name"].lower())),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--device", help="print one device's parameters instead of writing")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()
    data = build()

    if args.device:
        q = args.device.lower()
        hits = [d for d in data["devices"].values() if q in d["name"].lower()]
        if not hits:
            raise SystemExit(f"No device matching {args.device!r}.")
        for d in hits:
            print(f"\n{d['name']}  ({d['manufacturer']}, {len(d['items'])} parameters)")
            for i in d["items"]:
                print("   ", i)
        return

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n",
                        encoding="utf-8")
    print(f"Reason {data['reason_version']}: {data['device_count']} devices, "
          f"{data['item_count']} parameters, from {data['source_files']} files")
    print(f"-> {args.out}")


if __name__ == "__main__":
    main()
